config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root to: 'favors#index'
  resources :favors, except: [:new]
  resources :requested_favors, controller: 'favors', type: 'RequestedFavor', except: :new
  get 'request-a-favor', to: 'favors#new', type: 'RequestedFavor'
  resources :offered_favors, controller: 'favors', type: 'OfferedFavor', except: :new
  get 'offer-a-favor', to: 'favors#new', type: 'OfferedFavor'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :acceptances, only: [:create, :update]
  resources :activities, only: :index
  resources :rewards, only: :show
  resources :searches
end

app/models/favor.rb
class Favor < ActiveRecord::Base

  belongs_to :user
  has_many :acceptances

  has_many :compensations
  has_many :rewards, through: :compensations

  scope :requested, -> {where(type: 'RequestedFavor')}
  scope :offered, -> {where(type: 'OfferedFavor')}

  def self.types
    %w(RequestedFavor OfferedFavor)
  end

  def acceptor_user
    acceptances.find{ |ac| ac.accepted }.user
  end

  def has_accepted_acceptance?
    acceptances.any?{ |ac| ac.accepted }
  end
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  before_action :set_favor, except: [:index, :new, :create]
  before_action :set_favor_type

  def index
    @near_users = current_user.nearbys(30)
    @favors = type_class.all
  end

  def new
    @favor = type_class.new
  end

  def create
    @favor = type_class.new(favor_params)
    @favor.user_id = current_user.id

    if @favor.save
      redirect_to @favor, notice: "Favor created successfully!"
    else 
      render 'new'
    end
  end

  def edit
  end

  def update
    @favor.update_attributes(favor_params)
    if @favor.save
      redirect_to @favor, notice: "Updated"
    else
      render "update"
    end
  end

  def destroy
    @favor.destroy
    flash[:success] = "Favor deleted"
    redirect_to favors_path
  end

  private

  def favor_params
    params.require(type.underscore.to_sym).permit(:title, :description, :type, :completed, reward_ids: [])
  end

  def set_favor_type
    @type = type
  end

  def type
    Favor.types.include?(params[:type]) ? params[:type] : 'Favor'
  end

  def type_class
    type.constantize
  end

  def set_favor
    @favor = type_class.find(params[:id])
  end

  def current_resource
    @favor ||= Favor.find(params[:id]) if params[:id]
  end
end

app/helpers/favors_helper.rb
module FavorsHelper

  def set_new_page_header(type)
    if type == "RequestedFavor"
      "Request a Favor"
    elsif type == "OfferedFavor"
      "Offer a Favor"
    end
  end

  def set_show_page_header(type)
    if type == "RequestedFavor"
      "You requested this favor"
    elsif type == "OfferedFavor"
      "You offered this favor"
    end
  end

  def accepted_acceptance_user_link(favor)
    # last is here because without it the relationship 
    # returns instead of the object
    ac = favor.acceptances.where(accepted: true).last
    link_to ac.user.name, user_path(ac.user)
  end

  def set_acceptances_message(type, favor)
    if !favor.has_accepted_acceptance?
      if type == "RequestedFavor"
        "The following people would like to do you this favor"
      elsif type == "OfferedFavor"
        "The following people need this favor from you"
      end
    elsif favor.has_accepted_acceptance?
      if type == "RequestedFavor"
        "The following user has agreed to do you this favor"
      elsif type == "OfferedFavor"
        "You agreed to do the following user this favor"
      end
    end 
  end
end

app/views/favors/_favor_acceptor.html.erb
ACCEPTOR PAGE

app/views/favors/_favor_creator.html.erb
(CREATOR PAGE)
<h1><%= set_show_page_header(type) %></h1>

<%= link_to "Delete", favor, method: :delete %>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Rewards</th>
  </tr>
  <tr>
    <td><%= favor.title %></td>
    <td><%= favor.description %></td>
    <td><%= raw(favor.rewards.map{ |reward| raw(link_to(reward.title, reward_path(reward))) }.join(", ")) %></td>
  </tr>
</table>

<p><%= set_acceptances_message(type, favor) %></p>

<% if favor.has_accepted_acceptance? %>
  <%= accepted_acceptance_user_link(favor)%>
<% else %>
  <% favor.acceptances.each do |acceptance| %>
    <%= link_to acceptance.user.firstname, user_path(acceptance.user) %> <%= link_to "Accept", acceptance_path(acceptance),method: :put %><br />
  <% end %>
<% end %>

app/views/favors/_favor_visitor.html.erb
(VISITOR PAGE)
<h3>Favor by <%=  link_to favor.user.firstname, user_path(favor.user) %></h3>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= favor.title %></td>
    <td><%= favor.description %></td>
  </tr>
</table>

<%= link_to "Send a request for this favor", acceptances_path(acceptance: {favor_id: favor.id}), method: :post %>

app/views/favors/_form.html.erb
<%= form_for @favor do |f| %>

  <% if @favor.errors.any? %>
    <%= pluralize(@favor.errors.count, "error") %> prohibited this favor from being saved:</h2>
    <ul>
      <% @favor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="form-group">
    <%= f.label 'Choose rewards you can give: ' %>
    <%= f.collection_check_boxes(:reward_ids, Reward.all, :id, :title) %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

app/views/favors/index.html.erb
<%= link_to "Search Favors", new_search_path %>
<div class="col-md-6">
  <h1>Requested Favors</h1>
  <% @near_users.each do |user| %>
    <% user.favors.requested.each do |requested_favor| %>
      <% next if requested_favor.has_accepted_acceptance? %>
      <div class="panel panel-success">
        <div class="panel-heading">
          Favor requested by <%= link_to requested_favor.user.firstname, user_path(requested_favor.user) %><br />
        </div><!-- panel-heading -->
        <div class="panel-body">
          <%= link_to requested_favor.title, requested_favor_path(requested_favor) %> <%= requested_favor.completed %><br />
        </div><!-- panel-body -->
      </div><!-- panel panel-success -->
    <% end %>
  <% end %>
</div><!-- col-md-6 -->

<div class="col-md-6">
  <h1>Offered Favors</h1>
  <% @near_users.each do |user| %>
    <% user.favors.offered.each do |offered_favor| %>
      <% next if offered_favor.has_accepted_acceptance? %>
      <div class="panel panel-info">
        <div class="panel-heading">
          Favor offered by <%= link_to offered_favor.user.firstname, user_path(offered_favor.user) %>
        </div><!-- panel-heading -->
        <div class="panel-body">
          <%= link_to offered_favor.title, offered_favor_path(offered_favor) %><br />
        </div><!-- panel-body -->
      </div><!-- panel-info -->
    <% end %>
  <% end %>
</div><!-- col-md-6 -->

app/views/favors/new.html.erb
<h1><%= set_new_page_header(@type) %></h1>
<%= render 'form' %>

app/views/favors/show.html.erb
<% if @favor.user_id == current_user.id %>
  <%= render partial: 'favor_creator', locals: {favor: @favor, type: @type} %>
<% elsif !@favor.has_accepted_acceptance? %>
  <%= render partial: 'favor_visitor', locals: {favor: @favor} %>
<% elsif @favor.has_accepted_acceptance? && @favor.acceptor_user == current_user %>
  <%= render partial: 'favor_acceptor', locals: {favor: @favor} %>
<% else %>
  Plain show page
<% end %>