config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root to: 'favors#index'
  resources :favors, except: [:new]
  resources :requested_favors, controller: 'favors', type: 'RequestedFavor', except: :new
  get 'request-a-favor', to: 'favors#new', type: 'RequestedFavor'
  resources :offered_favors, controller: 'favors', type: 'OfferedFavor', except: :new
  get 'offer-a-favor', to: 'favors#new', type: 'OfferedFavor'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :acceptances, only: [:create, :update]
  resources :activities, only: :index
  resources :rewards, only: :show
  resources :searches
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_user_full_name
  
  has_many :favors
  has_many :acceptances
  has_many :activities

  has_secure_password

  geocoded_by :city
  after_validation :geocode, :if => :city_changed?

  def to_be_done_favors
    undones = user_acceptances_favors.find_all { |favor| !favor.completed }
    undones.map{ |undone| undone }
  end

  def done_favors
    dones = user_acceptances_favors.find_all { |favor| favor.completed }
    dones.map{ |done| done  }
  end

  def user_acceptances_favors
    self.acceptances.select { |ac| ac.accepted }.map{ |ac| ac.favor }
  end

  private

  def set_user_full_name
    self.name = "#{firstname}" + " " + "#{lastname}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user
  before_action :current_resource, only: :show

  def show 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :city, :password, :password_confirmation)
  end

  def current_resource
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= f.label "First name" %>
  <%= f.text_field :firstname %>

  <%= f.label "Last name" %>
  <%= f.text_field :lastname %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.firstname %>'s Profile</h1>

<table class="table">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>City</th>
    <th>Email</th>
  </tr>
  <tr>
    <td><%= @user.firstname %></td> 
    <td><%= @user.lastname %></td>
    <td><%= @user.city %></td>
    <td><%= @user.email %></td>
  </tr>
</table>

<div class="col-md-12">
  <div class="col-md-6">
    <h2>Requested Favors</h2>
    <ul class="list-group">
      <% @user.favors.requested.each do |requested_favor| %>
        <% next if requested_favor.completed %>
        <li class="list-group-item list-group-item-success">
          <%= link_to requested_favor.title, requested_favor_path(requested_favor) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-6">  
    <h2>Offered Favors</h2>
    <ul class="list-group">
      <% @user.favors.offered.each do |offered_favor| %>
        <% next if offered_favor.completed %>
        <li class="list-group-item list-group-item-success">
          <%= link_to offered_favor.title, offered_favor_path(offered_favor) %>
        </li>
      <% end %>
    </ul>
  </div>
</div><!-- col-md-12 -->

<div class="col-md-6">
  <h1>Past</h1>
  <div class="col-md-6">
    <h2>Recieved favors</h2>
  </div>

  <div class="col-md-6">
  <h2>Done Favors</h2>
    <ul class="list-group">
    <% @user.done_favors.each do |favor|%>
      <li class="list-group-item list-group-item-success">
        <%= link_to favor.title, favor_path(favor) %><br />
      </li>
    <% end %>
  </div>
</div><!-- col-md-12 -->

<div class="col-md-6">
  <h1>Future</h1>
  <div class="col-md-6">
    <h2>To be recieved favors</h2>
  </div>

  <div class="col-md-6">
  <h2>To be done Favors</h2>
  <ul class="list-group">
    <% @user.to_be_done_favors.each do |favor|%>
      <li class="list-group-item list-group-item-success">
        <%= link_to favor.title, favor_path(favor) %><br />
      </li>
    <% end %>
  </div>
</div><!-- col-md-12 -->

<h2>Favors you sent acceptance requests to</h2>